### ISSUE TITLE
Firmware upgrade

### ISSUE THREAD

**Issue by vaidyasr** [shadow-1/yi-hack-v3#103]
Can I upgrade the firmware from 2.1.0.0A_201703071456 to 2.1.0.0C_201710091352? I have currently installed 0.1.4-beta2

**Comment by shadow-1** [comment]
@vaidyasr 
With this version of yi-hack-v3 (or newer), it is safe to perform Xiaomi firmware updates.

**Comment by CrescendoFang** [comment]
Yi 17CN upgrade from 1.8.7.0C_201705091058 to 1.8.7.0D using 0.1.5 succeed, however the version remains the same 1.8.7.0C but the camera says up to date...

Strange....

**Comment by shadow-1** [comment]
@CrescendoFang 
Thanks for letting me know. I will have to download the new firmware, unpack it and see how it has changed from the previously released firmware.

**Comment by CrescendoFang** [comment]
@shadow-1 any news for this project?

**Comment by batrarobin** [comment]
Yes, I just updated it and it still works.
