### ISSUE TITLE
ProxyChains-ng Download Proxy List 

### ISSUE THREAD

**Issue by joycekhoo** [shadow-1/yi-hack-v3#106]
ERROR: Could not connect to freevpn.ninja, ensure that you are connectected to the Internet.

![proxy](https://user-images.githubusercontent.com/34940636/34438416-b1ea29dc-ece1-11e7-92f5-4102970a1715.png)

**Comment by shadow-1** [comment]
@joycekhoo 
There is another thread which describes the same issue. I will close this issue, please feel free to continue the discussion in the other thread:
Link to existing thread: https://github.com/shadow-1/yi-hack-v3/issues/102
