### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by erictong1** [shadow-1/yi-hack-v3#107]
freevpn.ninja gt problem so i cant enable my camera.can you make any Lan version for mi 1080p home?

**Comment by shadow-1** [comment]
@erictong1 
There is another thread which describes the same issue. I will close this issue, please feel free to continue the discussion in the other thread. The other thread describes a workaround for the time being.
Link to existing thread: https://github.com/shadow-1/yi-hack-v3/issues/102
