### ISSUE TITLE
Can I apply this hack straight on yi 1080p home that only works in china?

### ISSUE THREAD

**Issue by LaFed** [shadow-1/yi-hack-v3#110]
Just got a yi 1080p home and updated as soon as i got it... Now i wont be able to use it as it's only available for china user. Can I just apply this hack? or I need to downgrade the firmware to get it to work normally before applying the hack?

**Comment by shadow-1** [comment]
@LaFed
You can apply this hack directly. There is no need to downgrade first.

By the way, all Chinese versions of the yi 1080p home camera are region locked to Mainland China. Therefore you have to use this hack for the camera to work outside of China.

**Comment by LaFed** [comment]
awesome.... thanks for the quick reply!!
