### ISSUE TITLE
Pairing timedout

### ISSUE THREAD

**Issue by ronendayan** [shadow-1/yi-hack-v3#122]
Hi
I got the YI Dome
I put the files you wrote on the SD card (without the YI firmware file)
And now i can't access the camera
the http url doesn't work.
I try to reset the camera and put all 3 files on the SD card but without success,
Please advise what to do next

**Comment by ronendayan** [comment]
So i got the recovery image from here:
https://app.box.com/s/cibs7n1mgvhqaqjlidtveegu1uajt5yr
and the camera back to normal.
I will try to flash again the hack version
Thanks

**Comment by shadow-1** [comment]
@ronendayan 
Great that you managed to get to the Recovery image. This will get you back to stock firmware. Just try again and see if it works properly now.

**Comment by ronendayan** [comment]
Tested it again and its working fine,
Thanks
