### ISSUE TITLE
Unable to connect to freevpn.ninja

### ISSUE THREAD

**Issue by NeoDeGenero** [shadow-1/yi-hack-v3#135]
I've attempted to connect to the site via browsers, and proxied browers, seemed the site is down.

Anyone have any luck with this?

Cheers.

![freevnp ninja](https://user-images.githubusercontent.com/35796194/35377011-a5377e94-0201-11e8-86b7-620c4d3854f8.JPG)

**Comment by bola04053** [comment]
go http://spys.one/proxys/CN/
manual type in proxy on your front page , example like this : 

random_chain
chain_len = 1
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]
socks5 223.241.214.44 1217
socks5 211.95.255.42 1080
socks5 118.89.231.84 30687
socks5 119.29.163.54 1080
socks5 61.145.213.14 1080
socks5 218.58.210.233 1080
socks5 221.209.62.170 1080
socks5 117.135.132.107 3000

**Comment by NeoDeGenero** [comment]
Awesome, works great, thanks heaps!

**Comment by easycor90** [comment]
![image](https://user-images.githubusercontent.com/37905933/38094984-dc4856f2-33a1-11e8-971c-7ee5aaa77e23.png)
I've attempted to connect to the site via browsers, and proxied browers, seemed the site is down.
Anyone know how to fix it?

Thanks you so much

**Comment by williamwl1215** [comment]
hey your manual type server has all failed. 
and i try to type other servers and all test config failed. 

is there any problem or mistake i made? like type the wrong server address formate?

**Comment by adrianwy** [comment]
I have the same issue, all connections failed. Any other idea?
