### ISSUE TITLE
Binding success but not camera added in main menu

### ISSUE THREAD

**Issue by MatChung** [shadow-1/yi-hack-v3#16]
Thx for the hack. But I have a problem that I can not add the camera.

ProxyChains-ng is configured and I sure that the binding has completed successfully, but after returning to main screen of App, there is not camera shown.

Is there any help on this?

Thx.

![screenshot_20170502-021728](https://cloud.githubusercontent.com/assets/579044/25630287/290abf46-2f9f-11e7-93d2-b822b49abb19.png)

**Comment by shadow-1** [comment]
@MatChung 
This is a bit of an unusual problem. Most people have issues finding a working proxy server. Once a proxy server is found, everything tends to work without issues.

The problem you are having is an issue with the smartphone app itself.

A few things you can try:
* Try resetting and pair/bind the camera to your phone again.
* Make sure you have updated your smartphone app to the latest version.

**Comment by shadow-1** [comment]
@MatChung 
I have found out that this issue may be caused by having an old version of the smartphone app installed.
Also try the latest version of the hack as it has made configuring proxies much easier.
Feel free to open a new issue if you are still having issues.
