### ISSUE TITLE
yi-1080p-Dome does not pair after FW upgrade

### ISSUE THREAD

**Issue by Rhapsody02** [shadow-1/yi-hack-v3#218]
After firmware upgrade and reset of the camera, I re-start pairing process and go through all steps successfully up to connecting to wifi (also success), however then.... NOTHING and the pairing times out.

Any ideas, please?

EDIT: Some more facts.
- camera with original FW paired and worked just fine
- compared to originally working scenario, I have tried to use also 2nd wifi network I gave (2,4G only) when trying to pair with yi-hack, still timeout
- I am able to successfully flash older version of yi-hack fw, same results with pairing though
- I am NO LONGER able to flash original FW (maybe doing some mistake, I can download only file called "home_h20m" from original web whereas for yi hack "home_h20" + 1 more file are used.
When flashing original FW with m at the end, file is ignored and camera boots, if I rename without m, boot stuck with orange LED.

**Comment by Rhapsody02** [comment]
No reaction? :-/

One more thing I found out, the camera web interface is accessible after failed pairing.
If I cannot pair with yi-hack-v3, any idea how can I flash back the original firmware, please?

It does not begin flashing... Am not sure which file(s) and name(s) to use (tried multiple.

**Comment by lvnilesh** [comment]
Did you skip step 11 in https://github.com/shadow-1/yi-hack-v3#getting-started---step-by-step-guide

**Comment by Rhapsody02** [comment]
I guess that I deserved that, I missed I HAVE to disable the proxy settings, not optional.
I feel silly, but still it is great that it works now!

**MANY** thanks for your help!!!
