### ISSUE TITLE
Help required to fix the camera

### ISSUE THREAD

**Issue by vaidyasr** [shadow-1/yi-hack-v3#234]
I have accidentally renamed the /bin/busybox to /bin/busybox_org to accommodate the new busybox, after that I can't rename back to original. It says file system full and can't do any operations. After tried many options, I thought of rebooting may fix the issue. But the camera stays orange after reboot and don't have a idea how to fix it?. Could some one please help?

**Comment by shadow-1** [comment]
@vaidyasr 
Unfortunately you have killed your rootfs partition.
To recover from this, flash the stock firmware using the recovery images I linked to on the home page.
Then flash back to yi-hack-v3 firmware again. Everything will be back to normal afterwards.

**Comment by vaidyasr** [comment]
@shadow-1 worked perfectly. Thank you.
