### ISSUE TITLE
How can enable Telnet?

### ISSUE THREAD

**Issue by terlanks** [shadow-1/yi-hack-v3#240]
Now the telnet is disabled as default setting, how could I enable it and change the password. Since I need it access by HA.
Any suggestion? Thanks

**Comment by LordVanguard** [comment]
If you go to the IP address of the camera in your web browser, then navigate to system config, there is a setting there that will allow you to enable the telnet setting. This is if I am reading the main yi-hack-v3 information page correctly.

**Comment by terlanks** [comment]
Thanks, it's there:)
