### ISSUE TITLE
How do I config the Surveillance Station(synology's NAS) connect to Yi 1080p Dome

### ISSUE THREAD

**Issue by FisherMS** [shadow-1/yi-hack-v3#253]
The web URLr: http://yi-hack-v3  , I can access it.
Now, what do next ?

**Comment by neoKushan** [comment]
I don't think you can, the cameras don't do rtsp out of the box.

**Comment by shadow-1** [comment]
@neoKushan is correct. This firmware only supports the official smartphone app. Check out yi-hack-v4 as it is in the works.

**Comment by FisherMS** [comment]
ok,thank you.
