### ISSUE TITLE
Yi Dome 1080p not working

### ISSUE THREAD

**Issue by EnesLatifovic** [shadow-1/yi-hack-v3#255]
hi, i've tryed to flash the rootfs_h20 and the home_h20 but that is not working.
Current version is 1.9.2.x. Any proposal for me?

**Comment by aptonline** [comment]
What platform are you using to flash? I had the same issue with my Mac.  The .dms extension was removed in the finder but you need to get info on the files and uncheck the remove extension checkbox to fully remove it.

**Comment by EnesLatifovic** [comment]
I found the solution. Thanks
