### ISSUE TITLE
Yi Home 1080p Cam keep on restarting

### ISSUE THREAD

**Issue by vaidyasr** [shadow-1/yi-hack-v3#258]
My YiHome 1080p is keep on restarting after pairing successfully. Initially I suspect with the SD card, but the same symptoms even after the SD card has been removed. Anyone knows what could be the issue?

**Comment by shadow-1** [comment]
@vaidyasr 
I have not seen this issue. Just for my information, are you running any custom scripts or custom applications on the camera?

The camera has very little RAM, if the camera runs out of RAM, it is likely to restart on its own.
