### ISSUE TITLE
Xiaomi 1080P Smart Camera

### ISSUE THREAD

**Issue by afoninsky** [shadow-1/yi-hack-v3#265]
I have Xiaomi 1080P Smart Camera (like [this one](https://www.aliexpress.com/item/Original-Xiaomi-Mijia-New-1080P-IP-Camera-130-Degree-FOV-Night-Vision-2-4Ghz-Dual-band/32899846324.html)).

Can I use one of firmwares? And what firmware should I use? Thx

**Comment by nicmorais** [comment]
Hello
Please tell us the first four digits of the QR code in the back of camera.

**Comment by afoninsky** [comment]
Hello.

04CF*******

**Comment by nicmorais** [comment]
Unfortunately, this hack does not support your camera, neither yi-hack-v4 does.

**Comment by afoninsky** [comment]
Thx

**Comment by nicmorais** [comment]
@afoninsky but, if the developers get what cpu, ram and rom this device has, and a firmware dump, they can work to support your camera

**Comment by afoninsky** [comment]
I'll reopen issue then :) If developers contact me I'll try to provide information as far as I can.

**Comment by nicmorais** [comment]
@afoninsky take a look at this: [Filipowicz251/mijia-1080P-hacks](https://github.com/Filipowicz251/mijia-1080P-hacks)

**Comment by afoninsky** [comment]
Yep I got it thx. Kind of tricky but looks like it's the only way for now :(
https://github.com/Filipowicz251/mijia-1080P-hacks/issues/55
