### ISSUE TITLE
How can I apply it to the YI Home 1080p?

### ISSUE THREAD

**Issue by maysamsh** [shadow-1/yi-hack-v3#3]
How can I apply it to my cam? I'm using the latest hack which provides RTSP stream but I like to use the official app and bypass the region ban.

**Comment by shadow-1** [comment]
@maysamsh 
Unfortunately this custom firmware does not support RTSP at this stage.
At the moment it only supports the use of the official smartphone app and defeats the region ban.

**Comment by maysamsh** [comment]
@shadow-1 Do I need custom rootfs and home image files? I cannot find them here.

**Comment by shadow-1** [comment]
@maysamsh 
To use this firmware you need custom rootfs and home. They are available here:
https://github.com/shadow-1/yi-hack-v3/releases

**Comment by batrarobin** [comment]
@maysamsh
Do a bit of a reading before asking questions:
https://github.com/shadow-1/yi-hack-v3/blob/master/README.md

Here's where you would find the relevant files:
 https://github.com/shadow-1/yi-hack-v3/releases

Ensure that you have the correct filenames on your SD card and use a 16GB card or less, formatted with FAT32.

**Comment by maysamsh** [comment]
@batrarobin Thanks! I skipped the first few paragraphs.
