### ISSUE TITLE
Can startup.sh be deleted after device connected successfully ?

### ISSUE THREAD

**Issue by genz10** [shadow-1/yi-hack-v3#36]
Can startup.sh be deleted after device connected successfully ? or it should be in there forever ?

**Comment by shadow-1** [comment]
@genz10 
startup.sh can be deleted after the device connects successfully. The only drawback is that when the camera restarts, startup.sh will not exist and whatever extra commands you wanted to be executed automatically will not occur again.

For most people, startup.sh should exist forever to make sure those additional commands get executed every time the camera starts up.

**Comment by genz10** [comment]
@shadow-1 
I see, thanks for the answer!
