### ISSUE TITLE
Yi Home Camera 2 support

### ISSUE THREAD

**Issue by fjkum** [shadow-1/yi-hack-v3#38]
Hi,

I purchased the International version of Yi Home Camera 2 from https://yitechnology.com/yi-1080p-home-camera-2

Can I use your yi-hack-v3 y20 firmware for this?

Thank You.

**Comment by shadow-1** [comment]
@fjkum 
Unfortunately the Yi Home 2 is not supported with this firmware.
The Yi Home 2 firmware uses a completely different chipset to the original Yi Home.

The Yi Home 2 makes use of the Ambarella S2LM chip.
This firmware only supports cameras based on the HiSilicon Hi3518eV200 chipset.

This firmware linked below supports the Yi Home 2. However it looks like it is no longer being supported.
https://github.com/niclet/yi-hack-v2
