### ISSUE TITLE
Regional ban hack guide

### ISSUE THREAD

**Issue by hanson06** [shadow-1/yi-hack-v3#4]
Can provide step by step guide to configure proxychains-ng...no exprince on that

**Comment by junsheng89** [comment]
same here. @hanson06. can @shadow-1 or @xmflsct provide some guidance?

i was able to successfully flash rootfs partition & home partition, however, i am stuck at the configuration part. what changes are to be made on the ProxyChainNg configuration?

**Comment by xmflsct** [comment]
Simple explanation:

You only need to modify the last line of the configuration, namely, the socks proxy. The format is:
`socks4   PROXY_IP   PROXY_PORT` or `socks5   PROXY_IP   PROXY_PORT`.
You should try these proxies on your computer to make sure it is working. 
[https://whatismyipaddress.com/](https://whatismyipaddress.com/) Do try this https website to be sure that the proxy is based in mainland China, excluding Hong Kong and Macau. This webpage also verifies that the proxy supports SSL which is essential for the trick to work.

**Comment by djartemon** [comment]
What should I do if rootfs_v201 was not written to the SD card? How to put it if home_v201 was installed without it?

**Comment by shadow-1** [comment]
@hanson06 @junsheng89 
I have finally gotten around to writing a more detailed guide on how to use this hack.
Let me know if you have any issues.
