### ISSUE TITLE
Hack for new Xiaomi yi Cloud Camera

### ISSUE THREAD

**Issue by vaidyasr** [shadow-1/yi-hack-v3#43]
I found the new Xiaomi Cloud camera is cheap, but I am not sure whether there will be a SD card slot to hack. Anyone tested this one. http://item.jd.com/4230953.html

**Comment by shadow-1** [comment]
@vaidyasr 
I have not seen this camera before. I guess someone will have to try it and report back to us.

It is likely to be the same or similar to the Yi Home 17CN.

**Comment by vaidyasr** [comment]
Hope you have seen the firmware files. https://github.com/shadow-1/yi-hack-v3/issues/39#issuecomment-317642968

**Comment by shadow-1** [comment]
@vaidyasr 
Yes I did see the files you posted in the other thread. Thanks a lot for that.
