### ISSUE TITLE
Can i do a firmware update?

### ISSUE THREAD

**Issue by Dp4610yz** [shadow-1/yi-hack-v3#47]
Hi,

i am using the yi camera 1080p black dome camera....

I saw there is a update avail...can i update? will it break the whole thing?

Regards
Daniel

**Comment by shadow-1** [comment]
@Dp4610yz
If you are using the latest version of yi-hack-v3 (at the moment 0.1.4-beta2). It is safe to apply updates.

**Comment by Fa5g** [comment]
I'm using the last yi-hack-v3 version, can I update my YI Dome 1080 Cams with the last firmware update announced by Xiaomi number 1.9.2.0G_201807231514?

Thanks in advance for your reply.
