### ISSUE TITLE
How do I actually use the camera after installing the hack?

### ISSUE THREAD

**Issue by traslin** [shadow-1/yi-hack-v3#56]
I can access the camera via telnet and ftp, but I'm not sure how to use those protocols in a useful way. Specifically, I'd like to get add the camera to HomeAssistant, but I can't even figure out how to add it as a generic IP camera (expects a still image URL). Can someone point me in the right direction?

**Comment by shadow-1** [comment]
@traslin 
At the moment this firmware only supports using the official Xiaomi app. Telnet and FTP is useful for power users who like tinkering and learning how the camera works.

For example, I know some people have written a script to automatically sync the cameras recordings to Google Drive.
