### ISSUE TITLE
outdoor waterproof enclosure for Yi 1080p dome

### ISSUE THREAD

**Issue by bronzerain** [shadow-1/yi-hack-v3#57]
Has anyone tried to put the YI 1080P dome camera in a outdoor waterproof enclosure? Any ideas? I know some people have been doing this with the Amcrest indoor 1080p PTZ cameras.

**Comment by ver2go** [comment]
Not really an issue or right place for this, but on Slickdeals many have reported using Nest Cases listed on Amazon.  They were $8 a couple of months ago, but that seller sold out.  There are $14 ones now that are similar.  Many have stated to back the camera with foil for heat.

**Comment by zjxlsgh** [comment]
@bronzerain hello, have you solve IR problem for your Fang camera? i have the same needs, want IR perma off
