### ISSUE TITLE
Does this support the latest firmware 2.1.0.0B_201708041129home_y20m for Yi 1080p Home?

### ISSUE THREAD

**Issue by rdhood** [shadow-1/yi-hack-v3#61]
The lastest app out at the google play store requires 2.1.0.0B_201708041129home_y20m firmware on the Yi Home 1080p.   I noticed that your last checkin said something like "yi-hack-v3 no longer affected by Xiaomi firmware updates".   Does that mean that it will work with this latest version?

**Comment by shadow-1** [comment]
@rdhood 
If you are using the latest version of yi-hack-v3. You can safely perform the official Xiaomi updates.
