### ISSUE TITLE
Camera support question

### ISSUE THREAD

**Issue by arsaboo** [shadow-1/yi-hack-v3#65]
Wondering if either 
https://www.gearbest.com/ip-cameras/pp_693217.html
or 
https://www.gearbest.com/ip-cameras/pp_620813.html

can be used with the yi-hack firmware.

**Comment by shadow-1** [comment]
@arsaboo 
These cameras use a completely different hardware to what this firmware supports.
Have a look at this project: https://github.com/samtap/fang-hacks

That project supports the xiaofang camera. I don't think any custom firmware supports the dafang camera yet.
