### ISSUE TITLE
No more cloud feature

### ISSUE THREAD

**Issue by AppaloosaTech** [shadow-1/yi-hack-v3#72]
First of all, thanks for your great work, shadow-1!

Is it possible to "disable" the cloud feature, that no more data get out of the local network? (fritz-smh made it possible in his [YI hack](https://github.com/fritz-smh/yi-hack))

Thank you.

**Comment by shadow-1** [comment]
@AppaloosaTech 
At the moment, it is not possible to disable the cloud features. The camera only works with the official Xiaomi app at the moment. With the cloud features disabled, the official smartphone app will stop working.

This will definitely be incorporated when RTSP support gets developed.
