### ISSUE TITLE
updating the firmware

### ISSUE THREAD

**Issue by Darkmagister** [shadow-1/yi-hack-v3#80]
Hello I'm using your modded firmware in a yi 1080p dome camera
Version

Camera
    Yi 1080p Dome
Base Firmware
    1.9.2.0F_201706211024
yi-hack-v3 Firmware
    0.1.4-beta2

But the yi home app ask me to update to
1.9.2.0F_201708041132

Can I just do the update or I will loose your mod?
Thanks

**Comment by shadow-1** [comment]
@Darkmagister 
Because you are using version 0.1.4-beta2 of the hack, you can safely perform the official Xiaomi firmware update without affecting the mod.

When the camera restarts after the update, yi-hack-v3 will restore itself and be operational just as before.

**Comment by Darkmagister** [comment]
@shadow-1 thanks a lot I'll update then
