### ISSUE TITLE
Yi Home27US

### ISSUE THREAD

**Issue by josemonino** [shadow-1/yi-hack-v3#88]
Hello, 

First of all thanks for this great project.
I have the Yi Home 27US (I think because it's written 27USY197WJ on the back) already working with the original firm... 

I tried to install this firm inserting a formatted 16GB sd card with the files rootfs_y18 and home_y18 as step 2 says. Everything was working like it's written but when trying to show the camera the QR code:

0. Blinking yellow
1. Blue led  starts blinking for around 10 seconds
2. It turns to steady yellow for around 10 seconds
3. I can heard the "click" when the camera starts and it comes to blinking yellow

Then I tried to reset the camera and leave it without sd and everything is the same but with voice:
0. Waiting to connect
1. QR code scan is successful, connecting to WiFi
2. ...
3. Welcome to Yi Home Camera... Waiting to connect

Do you know if I can do anything to resolve it?
Thanks again

**Comment by shadow-1** [comment]
@josemonino
Try using the firmware file from this post: https://github.com/shadow-1/yi-hack-v3/issues/40#issuecomment-315593035

I have not officially released the 27US compatible firmware just yet.

**Comment by josemonino** [comment]
Thanks a lot! It's working 👍 👍 👍

**Comment by shadow-1** [comment]
@josemonino 
Glad to hear that it worked out.
