### ISSUE TITLE
'startup.sh' does not start after boot.

### ISSUE THREAD

**Issue by insantr** [shadow-1/yi-hack-v3#9]
I created `startup.sh` in root dir on sdcard, after reboot it did not run
```
/tmp/sd # ls -la startup.sh
-rwxr-xr-x    1 root     root            29 Apr 16 00:24 startup.sh

/tmp/sd # cat startup.sh
echo test > /tmp/sd/test.log

/tmp/sd # ls -la test.log
ls: test.log: No such file or directory
```

__Camera__ Yi Dome
__Base Firmware__ 1.9.1.0G_201701161401
__yi-hack-v3 Firmware__ 0.1.2

**Comment by shadow-1** [comment]
@insantr 
Good find. I never properly used the startup.sh script. I added it as a feature as it is very easy to implement and may be useful for some people. It is useful if you accidentally disabled telnet server and web server through the web interface. 😜 

I have tested it and found the issue to be with the way I was starting up the FTP server. This issue will get corrected in the next release of the firmware. In the mean time, change Line 20 within `/home/app/system.sh` from:
`tcpsvd -vE 0.0.0.0 21 ftpd -w`
to:
`tcpsvd -vE 0.0.0.0 21 ftpd -w &`
